# Generated by Django 5.1.1 on 2024-09-20 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tema', models.CharField(max_length=255)),
                ('questoes', models.ManyToManyField(through='simulados.QuestaoSimulado', to='questoes.questao')),
            ],
        ),
        migrations.AddField(
            model_name='questaosimulado',
            name='simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.simulado'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.simulado')),
            ],
            options={
                'unique_together': {('simulado', 'questao', 'usuario')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='questaosimulado',
            unique_together={('simulado', 'questao')},
        ),
    ]
